version: '3'
services:
  email-templates-mock:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - ./mock-apis/email-templates:/config

  recipients-mock:
    image: mockserver/mockserver
    ports:
      - "1081:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - ./mock-apis/recipients:/config
